### PR TITLE
About page

### PR DESCRIPTION
**Pull request by mansa-susa**
Pull Request for the About Page of My mobile Portfolio website

### CODE REVIEW

**Review by williamrolando88 — COMMENTED** [review]
Hi @mansa-susa , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that you're not using properly GitHub flow for your project (you are not merging your changes in `main` and creating a new branch for the new features).
- Your PR doesn't have a README file, if you merge and create a new branch this won't be an issue

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by williamrolando88** [comment]
Also, please don't delete any previous review, system mark this review as the 3rd one for your current exercise

**Comment by mansa-susa** [comment]
Thank you I wanted to pull two requests simultaneously, I have merged the approved one with main now and I'm requesting PR  with the About page now.

**Comment by mansa-susa** [comment]
The webhint linter error says I can not use ul as a child of ul, I think it needs to be fixed because of nested lists.

**Review by AnselemOdims — APPROVED** [review]
### Hi  @mansa-susa 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions
- [ ] The buttress the point the previous reviewer made, please ensure not to merge a PR that is not approved yet

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
